//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogic.MessageEnglish", typeof(MessageEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type Added.
        /// </summary>
        internal static string CustomerTypeAdded {
            get {
                return ResourceManager.GetString("CustomerTypeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type Deleted Successfully.
        /// </summary>
        internal static string CustomerTypeDeleted {
            get {
                return ResourceManager.GetString("CustomerTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type Updated.
        /// </summary>
        internal static string CustomerTypeUpdated {
            get {
                return ResourceManager.GetString("CustomerTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Added.
        /// </summary>
        internal static string DescAdded {
            get {
                return ResourceManager.GetString("DescAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Enter Name.
        /// </summary>
        internal static string EmptyCustomerName {
            get {
                return ResourceManager.GetString("EmptyCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Customer Type Name.
        /// </summary>
        internal static string EmptyCustomerTypeName {
            get {
                return ResourceManager.GetString("EmptyCustomerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email id.
        /// </summary>
        internal static string EmptyEmailId {
            get {
                return ResourceManager.GetString("EmptyEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Mobile No.
        /// </summary>
        internal static string EmptyMobileNo {
            get {
                return ResourceManager.GetString("EmptyMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Role Name.
        /// </summary>
        internal static string EmptyRoleName {
            get {
                return ResourceManager.GetString("EmptyRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Stage Name.
        /// </summary>
        internal static string EmptyStageName {
            get {
                return ResourceManager.GetString("EmptyStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Vehicle Model Name.
        /// </summary>
        internal static string EmptyVehicleModel {
            get {
                return ResourceManager.GetString("EmptyVehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Vehicle Name.
        /// </summary>
        internal static string EmptyVehicleName {
            get {
                return ResourceManager.GetString("EmptyVehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter workshop name.
        /// </summary>
        internal static string EmptyWorkshopName {
            get {
                return ResourceManager.GetString("EmptyWorkshopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is already exist.
        /// </summary>
        internal static string ExistEmailId {
            get {
                return ResourceManager.GetString("ExistEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No is already exist.
        /// </summary>
        internal static string ExistMobileNo {
            get {
                return ResourceManager.GetString("ExistMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id or password is incorrect.
        /// </summary>
        internal static string IncorrectEmailPwd {
            get {
                return ResourceManager.GetString("IncorrectEmailPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EmailId.
        /// </summary>
        internal static string InvalidEmailId {
            get {
                return ResourceManager.GetString("InvalidEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details Created.
        /// </summary>
        internal static string JobCreated {
            get {
                return ResourceManager.GetString("JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job started.
        /// </summary>
        internal static string Jobstarted {
            get {
                return ResourceManager.GetString("Jobstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobStatus Deleted Successfully.
        /// </summary>
        internal static string JobStatusDeleted {
            get {
                return ResourceManager.GetString("JobStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobStatus Updated.
        /// </summary>
        internal static string JobStatusUpdated {
            get {
                return ResourceManager.GetString("JobStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Customer Type Found.
        /// </summary>
        internal static string NoCustomerTypeFound {
            get {
                return ResourceManager.GetString("NoCustomerTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Role Found.
        /// </summary>
        internal static string NoRoleFound {
            get {
                return ResourceManager.GetString("NoRoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stage Found.
        /// </summary>
        internal static string NoStageFound {
            get {
                return ResourceManager.GetString("NoStageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Found.
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vehicle Make Found.
        /// </summary>
        internal static string NoVehicleMakeFound {
            get {
                return ResourceManager.GetString("NoVehicleMakeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vehicle Model Found.
        /// </summary>
        internal static string NoVehicleModelFound {
            get {
                return ResourceManager.GetString("NoVehicleModelFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Added.
        /// </summary>
        internal static string PartsAdded {
            get {
                return ResourceManager.GetString("PartsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Added.
        /// </summary>
        internal static string PriceAdded {
            get {
                return ResourceManager.GetString("PriceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Added.
        /// </summary>
        internal static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Deleted Successfully.
        /// </summary>
        internal static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Updated.
        /// </summary>
        internal static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Customer Type.
        /// </summary>
        internal static string SelectCustomerType {
            get {
                return ResourceManager.GetString("SelectCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Vehicle Make.
        /// </summary>
        internal static string SelectVehicleMake {
            get {
                return ResourceManager.GetString("SelectVehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Workshop.
        /// </summary>
        internal static string SelectWorkshop {
            get {
                return ResourceManager.GetString("SelectWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Added.
        /// </summary>
        internal static string StageAdded {
            get {
                return ResourceManager.GetString("StageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Deleted Successfully.
        /// </summary>
        internal static string StageDeleted {
            get {
                return ResourceManager.GetString("StageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Updated.
        /// </summary>
        internal static string StageUpdated {
            get {
                return ResourceManager.GetString("StageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added.
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive.
        /// </summary>
        internal static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Updated.
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Make Added.
        /// </summary>
        internal static string VehicleMakeAdded {
            get {
                return ResourceManager.GetString("VehicleMakeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Make Deleted Successfully.
        /// </summary>
        internal static string VehicleMakeDeleted {
            get {
                return ResourceManager.GetString("VehicleMakeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Make Updated.
        /// </summary>
        internal static string VehicleMakeUpdated {
            get {
                return ResourceManager.GetString("VehicleMakeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model Added.
        /// </summary>
        internal static string VehicleModelAdded {
            get {
                return ResourceManager.GetString("VehicleModelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model Deleted Successfully.
        /// </summary>
        internal static string VehicleModelDeleted {
            get {
                return ResourceManager.GetString("VehicleModelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model Updated.
        /// </summary>
        internal static string VehicleModelUpdated {
            get {
                return ResourceManager.GetString("VehicleModelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Added.
        /// </summary>
        internal static string WorkshopAdded {
            get {
                return ResourceManager.GetString("WorkshopAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Deleted Successfully.
        /// </summary>
        internal static string WorkshopDeleted {
            get {
                return ResourceManager.GetString("WorkshopDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Updated.
        /// </summary>
        internal static string WorkshopUpdated {
            get {
                return ResourceManager.GetString("WorkshopUpdated", resourceCulture);
            }
        }
    }
}
