//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageArabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageArabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogic.MessageArabic", typeof(MessageArabic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة نوع العميل.
        /// </summary>
        internal static string CustomerTypeAdded {
            get {
                return ResourceManager.GetString("CustomerTypeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث نوع العميل.
        /// </summary>
        internal static string CustomerTypeDeleted {
            get {
                return ResourceManager.GetString("CustomerTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث نوع العميل.
        /// </summary>
        internal static string CustomerTypeUpdated {
            get {
                return ResourceManager.GetString("CustomerTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة الوصف.
        /// </summary>
        internal static string DescAdded {
            get {
                return ResourceManager.GetString("DescAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم.
        /// </summary>
        internal static string EmptyCustomerName {
            get {
                return ResourceManager.GetString("EmptyCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmptyCustomerTypeName {
            get {
                return ResourceManager.GetString("EmptyCustomerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال عنوان البريد الإلكتروني.
        /// </summary>
        internal static string EmptyEmailId {
            get {
                return ResourceManager.GetString("EmptyEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رقم الجوال.
        /// </summary>
        internal static string EmptyMobileNo {
            get {
                return ResourceManager.GetString("EmptyMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم الدور.
        /// </summary>
        internal static string EmptyRoleName {
            get {
                return ResourceManager.GetString("EmptyRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم المرحلة.
        /// </summary>
        internal static string EmptyStageName {
            get {
                return ResourceManager.GetString("EmptyStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم طراز السيارة.
        /// </summary>
        internal static string EmptyVehicleModel {
            get {
                return ResourceManager.GetString("EmptyVehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم المركبة.
        /// </summary>
        internal static string EmptyVehicleName {
            get {
                return ResourceManager.GetString("EmptyVehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم الورشة.
        /// </summary>
        internal static string EmptyWorkshopName {
            get {
                return ResourceManager.GetString("EmptyWorkshopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف البريد الإلكتروني موجود بالفعل.
        /// </summary>
        internal static string ExistEmailId {
            get {
                return ResourceManager.GetString("ExistEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال موجود بالفعل.
        /// </summary>
        internal static string ExistMobileNo {
            get {
                return ResourceManager.GetString("ExistMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف البريد الإلكتروني أو كلمة المرور غير صحيحة.
        /// </summary>
        internal static string IncorrectEmailPwd {
            get {
                return ResourceManager.GetString("IncorrectEmailPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف البريد الإلكتروني غير صالح.
        /// </summary>
        internal static string InvalidEmailId {
            get {
                return ResourceManager.GetString("InvalidEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء تفاصيل الوظيفة.
        /// </summary>
        internal static string JobCreated {
            get {
                return ResourceManager.GetString("JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدأت المهمة.
        /// </summary>
        internal static string Jobstarted {
            get {
                return ResourceManager.GetString("Jobstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف حالة العمل بنجاح.
        /// </summary>
        internal static string JobStatusDeleted {
            get {
                return ResourceManager.GetString("JobStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث حالة الوظيفة.
        /// </summary>
        internal static string JobStatusUpdated {
            get {
                return ResourceManager.GetString("JobStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على نوع العميل.
        /// </summary>
        internal static string NoCustomerTypeFound {
            get {
                return ResourceManager.GetString("NoCustomerTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على دور.
        /// </summary>
        internal static string NoRoleFound {
            get {
                return ResourceManager.GetString("NoRoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على أي مرحلة.
        /// </summary>
        internal static string NoStageFound {
            get {
                return ResourceManager.GetString("NoStageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المستخدم.
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على نوع السيارة.
        /// </summary>
        internal static string NoVehicleMakeFound {
            get {
                return ResourceManager.GetString("NoVehicleMakeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على طراز السيارة.
        /// </summary>
        internal static string NoVehicleModelFound {
            get {
                return ResourceManager.GetString("NoVehicleModelFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة الأجزاء.
        /// </summary>
        internal static string PartsAdded {
            get {
                return ResourceManager.GetString("PartsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة السعر.
        /// </summary>
        internal static string PriceAdded {
            get {
                return ResourceManager.GetString("PriceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة الدور.
        /// </summary>
        internal static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الدور بنجاح.
        /// </summary>
        internal static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث الدور.
        /// </summary>
        internal static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء تحديد نوع العميل.
        /// </summary>
        internal static string SelectCustomerType {
            get {
                return ResourceManager.GetString("SelectCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء تحديد نوع السيارة.
        /// </summary>
        internal static string SelectVehicleMake {
            get {
                return ResourceManager.GetString("SelectVehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدد ورشة العمل.
        /// </summary>
        internal static string SelectWorkshop {
            get {
                return ResourceManager.GetString("SelectWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة المرحلة.
        /// </summary>
        internal static string StageAdded {
            get {
                return ResourceManager.GetString("StageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف حالة العمل بنجاح.
        /// </summary>
        internal static string StageDeleted {
            get {
                return ResourceManager.GetString("StageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث المرحلة.
        /// </summary>
        internal static string StageUpdated {
            get {
                return ResourceManager.GetString("StageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة المستخدم.
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المستخدم بنجاح.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير نشط.
        /// </summary>
        internal static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث المستخدم.
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة طراز السيارة.
        /// </summary>
        internal static string VehicleMakeAdded {
            get {
                return ResourceManager.GetString("VehicleMakeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف نوع المركبة بنجاح.
        /// </summary>
        internal static string VehicleMakeDeleted {
            get {
                return ResourceManager.GetString("VehicleMakeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث طراز السيارة.
        /// </summary>
        internal static string VehicleMakeUpdated {
            get {
                return ResourceManager.GetString("VehicleMakeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة طراز السيارة.
        /// </summary>
        internal static string VehicleModelAdded {
            get {
                return ResourceManager.GetString("VehicleModelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف طراز السيارة بنجاح.
        /// </summary>
        internal static string VehicleModelDeleted {
            get {
                return ResourceManager.GetString("VehicleModelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث طراز السيارة.
        /// </summary>
        internal static string VehicleModelUpdated {
            get {
                return ResourceManager.GetString("VehicleModelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة ورشة العمل.
        /// </summary>
        internal static string WorkshopAdded {
            get {
                return ResourceManager.GetString("WorkshopAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف ورشة العمل بنجاح.
        /// </summary>
        internal static string WorkshopDeleted {
            get {
                return ResourceManager.GetString("WorkshopDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث ورشة العمل.
        /// </summary>
        internal static string WorkshopUpdated {
            get {
                return ResourceManager.GetString("WorkshopUpdated", resourceCulture);
            }
        }
    }
}
